apiVersion: v1
kind: Pod
metadata:
  name: pod6
spec:
  schedulerName: scheduler
  containers:
  - name: example-container
    image: nginx
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "0.5"
        memory: "512Mi"
